# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ShaloodSexeeeh.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(769, 562)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.ImageTwoViewChoice = QtWidgets.QComboBox(self.tab)
        self.ImageTwoViewChoice.setObjectName("ImageTwoViewChoice")
        self.ImageTwoViewChoice.addItem("")
        self.ImageTwoViewChoice.addItem("")
        self.ImageTwoViewChoice.addItem("")
        self.ImageTwoViewChoice.addItem("")
        self.ImageTwoViewChoice.addItem("")
        self.gridLayout.addWidget(self.ImageTwoViewChoice, 2, 2, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ImageOneViewChoice = QtWidgets.QComboBox(self.tab)
        self.ImageOneViewChoice.setObjectName("ImageOneViewChoice")
        self.ImageOneViewChoice.addItem("")
        self.ImageOneViewChoice.addItem("")
        self.ImageOneViewChoice.addItem("")
        self.ImageOneViewChoice.addItem("")
        self.ImageOneViewChoice.addItem("")
        self.verticalLayout_2.addWidget(self.ImageOneViewChoice)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ImageOneview = PlotWidget(self.tab)
        self.ImageOneview.setObjectName("ImageOneview")
        self.horizontalLayout_2.addWidget(self.ImageOneview)
        self.ImageOneComponent = PlotWidget(self.tab)
        self.ImageOneComponent.setObjectName("ImageOneComponent")
        self.horizontalLayout_2.addWidget(self.ImageOneComponent)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.Browser = QtWidgets.QPushButton(self.tab)
        self.Browser.setObjectName("Browser")
        self.gridLayout.addWidget(self.Browser, 3, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ImageTwoView = PlotWidget(self.tab)
        self.ImageTwoView.setObjectName("ImageTwoView")
        self.horizontalLayout_3.addWidget(self.ImageTwoView)
        self.ImageTwoComponent = PlotWidget(self.tab)
        self.ImageTwoComponent.setObjectName("ImageTwoComponent")
        self.horizontalLayout_3.addWidget(self.ImageTwoComponent)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.WarningTabOne = QtWidgets.QLabel(self.tab)
        self.WarningTabOne.setObjectName("WarningTabOne")
        self.gridLayout.addWidget(self.WarningTabOne, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ComponentTwoChocie = QtWidgets.QComboBox(self.tab_2)
        self.ComponentTwoChocie.setObjectName("ComponentTwoChocie")
        self.ComponentTwoChocie.addItem("")
        self.ComponentTwoChocie.addItem("")
        self.ComponentTwoChocie.addItem("")
        self.ComponentTwoChocie.addItem("")
        self.ComponentTwoChocie.addItem("")
        self.ComponentTwoChocie.addItem("")
        self.ComponentTwoChocie.addItem("")
        self.gridLayout_2.addWidget(self.ComponentTwoChocie, 4, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.ModifiedOne = PlotWidget(self.tab_2)
        self.ModifiedOne.setObjectName("ModifiedOne")
        self.verticalLayout_3.addWidget(self.ModifiedOne)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 5, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.ModifiefTwo = PlotWidget(self.tab_2)
        self.ModifiefTwo.setObjectName("ModifiefTwo")
        self.verticalLayout_4.addWidget(self.ModifiefTwo)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 5, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.ImageMixerOneChoice = QtWidgets.QComboBox(self.tab_2)
        self.ImageMixerOneChoice.setObjectName("ImageMixerOneChoice")
        self.ImageMixerOneChoice.addItem("")
        self.ImageMixerOneChoice.addItem("")
        self.ImageMixerOneChoice.addItem("")
        self.horizontalLayout.addWidget(self.ImageMixerOneChoice)
        self.MixerSliderOne = QtWidgets.QSlider(self.tab_2)
        self.MixerSliderOne.setOrientation(QtCore.Qt.Horizontal)
        self.MixerSliderOne.setObjectName("MixerSliderOne")
        self.MixerSliderOne.setMinimum(0)
        self.MixerSliderOne.setMaximum(100)
        self.horizontalLayout.addWidget(self.MixerSliderOne)
        self.SliderOneValue = QtWidgets.QLabel(self.tab_2)
        self.SliderOneValue.setObjectName("SliderOneValue")
        self.horizontalLayout.addWidget(self.SliderOneValue)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.ComponentOneChoice = QtWidgets.QComboBox(self.tab_2)
        self.ComponentOneChoice.setObjectName("ComponentOneChoice")
        self.ComponentOneChoice.addItem("")
        self.ComponentOneChoice.addItem("")
        self.ComponentOneChoice.addItem("")
        self.ComponentOneChoice.addItem("")
        self.ComponentOneChoice.addItem("")
        self.ComponentOneChoice.addItem("")
        self.ComponentOneChoice.addItem("")
        self.gridLayout_2.addWidget(self.ComponentOneChoice, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.OutputChoice = QtWidgets.QComboBox(self.tab_2)
        self.OutputChoice.setObjectName("OutputChoice")
        self.OutputChoice.addItem("")
        self.OutputChoice.addItem("")
        self.OutputChoice.addItem("")
        self.horizontalLayout_4.addWidget(self.OutputChoice)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.ImageMixerTwoChoice = QtWidgets.QComboBox(self.tab_2)
        self.ImageMixerTwoChoice.setObjectName("ImageMixerTwoChoice")
        self.ImageMixerTwoChoice.addItem("")
        self.ImageMixerTwoChoice.addItem("")
        self.ImageMixerTwoChoice.addItem("")
        self.horizontalLayout_5.addWidget(self.ImageMixerTwoChoice)
        self.MixerSliderTwo = QtWidgets.QSlider(self.tab_2)
        self.MixerSliderTwo.setOrientation(QtCore.Qt.Horizontal)
        self.MixerSliderTwo.setObjectName("MixerSliderTwo")
        self.MixerSliderTwo.setMinimum(0)
        self.MixerSliderTwo.setMaximum(100)
        self.horizontalLayout_5.addWidget(self.MixerSliderTwo)
        self.SliderTwoValue = QtWidgets.QLabel(self.tab_2)
        self.SliderTwoValue.setObjectName("SliderTwoValue")
        self.horizontalLayout_5.addWidget(self.SliderTwoValue)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 3, 0, 1, 2)
        self.WarningTabTwo = QtWidgets.QLabel(self.tab_2)
        self.WarningTabTwo.setObjectName("WarningTabTwo")
        self.gridLayout_2.addWidget(self.WarningTabTwo, 6, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Image2!"))
        self.label.setText(_translate("MainWindow", "Image1!"))
        self.ImageTwoViewChoice.setItemText(0, _translate("MainWindow", "Choose a Component"))
        self.ImageTwoViewChoice.setItemText(1, _translate("MainWindow", "Mag"))
        self.ImageTwoViewChoice.setItemText(2, _translate("MainWindow", "Phase"))
        self.ImageTwoViewChoice.setItemText(3, _translate("MainWindow", "Real"))
        self.ImageTwoViewChoice.setItemText(4, _translate("MainWindow", "Img"))
        self.ImageOneViewChoice.setItemText(0, _translate("MainWindow", "Choose a Component:"))
        self.ImageOneViewChoice.setItemText(1, _translate("MainWindow", "Mag"))
        self.ImageOneViewChoice.setItemText(2, _translate("MainWindow", "Phase"))
        self.ImageOneViewChoice.setItemText(3, _translate("MainWindow", "Real"))
        self.ImageOneViewChoice.setItemText(4, _translate("MainWindow", "Img"))
        self.Browser.setText(_translate("MainWindow", "UploadImage"))
        self.WarningTabOne.setText(_translate("MainWindow", "Load Your Image!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.ComponentTwoChocie.setItemText(0, _translate("MainWindow", "Choose Your Mixer:"))
        self.ComponentTwoChocie.setItemText(1, _translate("MainWindow", "Mag"))
        self.ComponentTwoChocie.setItemText(2, _translate("MainWindow", "Phase"))
        self.ComponentTwoChocie.setItemText(3, _translate("MainWindow", "Real"))
        self.ComponentTwoChocie.setItemText(4, _translate("MainWindow", "Imag"))
        self.ComponentTwoChocie.setItemText(5, _translate("MainWindow", "UniMag"))
        self.ComponentTwoChocie.setItemText(6, _translate("MainWindow", "UniPhase"))
        self.label_3.setText(_translate("MainWindow", "OutputOne"))
        self.label_4.setText(_translate("MainWindow", "OutputTwo"))
        self.label_6.setText(_translate("MainWindow", "ComponentOne"))
        self.ImageMixerOneChoice.setItemText(0, _translate("MainWindow", "Choose An Image:"))
        self.ImageMixerOneChoice.setItemText(1, _translate("MainWindow", "ImageOne"))
        self.ImageMixerOneChoice.setItemText(2, _translate("MainWindow", "ImageTwo"))
        self.SliderOneValue.setText(_translate("MainWindow", "00"))
        self.ComponentOneChoice.setItemText(0, _translate("MainWindow", "Choose Your Mixer"))
        self.ComponentOneChoice.setItemText(1, _translate("MainWindow", "Mag"))
        self.ComponentOneChoice.setItemText(2, _translate("MainWindow", "Phase"))
        self.ComponentOneChoice.setItemText(3, _translate("MainWindow", "Real"))
        self.ComponentOneChoice.setItemText(4, _translate("MainWindow", "Imag"))
        self.ComponentOneChoice.setItemText(5, _translate("MainWindow", "UniMag"))
        self.ComponentOneChoice.setItemText(6, _translate("MainWindow", "UniPhase"))
        self.label_5.setText(_translate("MainWindow", "Mixer Output to :"))
        self.OutputChoice.setItemText(0, _translate("MainWindow", "Choose Output"))
        self.OutputChoice.setItemText(1, _translate("MainWindow", "OutPutOne"))
        self.OutputChoice.setItemText(2, _translate("MainWindow", "OutputTwo"))
        self.label_7.setText(_translate("MainWindow", "ComponentTwo"))
        self.ImageMixerTwoChoice.setItemText(0, _translate("MainWindow", "Choose An Image"))
        self.ImageMixerTwoChoice.setItemText(1, _translate("MainWindow", "ImageOne"))
        self.ImageMixerTwoChoice.setItemText(2, _translate("MainWindow", "ImageTwo"))
        self.SliderTwoValue.setText(_translate("MainWindow", "00"))
        self.WarningTabTwo.setText(_translate("MainWindow", "Make Your Mixer!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
from pyqtgraph import PlotWidget
